services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    environment:
      - REDIS_DATA_PATH=${REDIS_DATA_PATH:-./data}

  snappass:
    build: .
    image: snappass
    container_name: snappass
    ports:
      - "5200:5000"
    restart: unless-stopped
    stop_signal: SIGINT
    environment:
      - REDIS_HOST=redis
      - NO_SSL=True
    depends_on:
      - redis

volumes:
  redis-data: